"""Causality-first contracts for the paper-only AI Trader Research Lab."""

from .accounting import AccountSnapshot, PortfolioLedger, Position
from .causality import (
    AvailabilityCache,
    FeatureLineage,
    FeaturePoint,
    TrainOnlyStandardizer,
    causal_shift,
    fill_missing,
    trailing_mean,
)
from .contracts import (
    Bar,
    CausalityViolation,
    EventTime,
    FutureAccessError,
    Instrument,
    MarketEvent,
    OddsSnapshot,
    OutcomeSettlement,
    Partition,
    Provenance,
    Quote,
    Tick,
    TradingResearchError,
    Venue,
)
from .dataset import (
    DataProviderPort,
    Dataset,
    DatasetVersion,
    InMemoryDataProvider,
    TemporalView,
    ValidationIssue,
    ValidationReport,
    event_sort_key,
)
from .orders import (
    ExecutionPolicy,
    OrderIntent,
    OrderState,
    OrderType,
    RiskApprovedOrder,
    Side,
    SimulatedFill,
    apply_slippage,
    fee_for,
)
from .persistence import TradingStateRepository
from .replay import OrderUpdate, ReplayBook, ReplayPhase, SimulationExecutionEngine, TimeSlice
from .risk import RiskEngine, RiskLimits, RiskRejected, RiskState
from .strategy import DecisionContext, OrderStrategy, Strategy, StrategyDecision

__all__ = [
    "AccountSnapshot",
    "AvailabilityCache",
    "Bar",
    "CausalityViolation",
    "DataProviderPort",
    "Dataset",
    "DatasetVersion",
    "DecisionContext",
    "EventTime",
    "ExecutionPolicy",
    "FeatureLineage",
    "FeaturePoint",
    "FutureAccessError",
    "InMemoryDataProvider",
    "Instrument",
    "MarketEvent",
    "OddsSnapshot",
    "OrderIntent",
    "OrderState",
    "OrderStrategy",
    "OrderType",
    "OrderUpdate",
    "OutcomeSettlement",
    "Partition",
    "PortfolioLedger",
    "Position",
    "Provenance",
    "Quote",
    "ReplayBook",
    "ReplayPhase",
    "RiskApprovedOrder",
    "RiskEngine",
    "RiskLimits",
    "RiskRejected",
    "RiskState",
    "Side",
    "SimulatedFill",
    "SimulationExecutionEngine",
    "Strategy",
    "StrategyDecision",
    "TemporalView",
    "Tick",
    "TimeSlice",
    "TradingResearchError",
    "TradingStateRepository",
    "TrainOnlyStandardizer",
    "ValidationIssue",
    "ValidationReport",
    "Venue",
    "apply_slippage",
    "causal_shift",
    "event_sort_key",
    "fee_for",
    "fill_missing",
    "trailing_mean",
]
