"""Causality-first contracts for the paper-only AI Trader Research Lab."""

from .accounting import AccountSnapshot, PortfolioLedger, Position
from .causality import (
    AvailabilityCache,
    FeatureLineage,
    FeaturePoint,
    TrainOnlyStandardizer,
    causal_shift,
    fill_missing,
    trailing_mean,
)
from .contracts import (
    Bar,
    CausalityViolation,
    EventTime,
    FutureAccessError,
    Instrument,
    MarketEvent,
    OddsSnapshot,
    OutcomeSettlement,
    Partition,
    Provenance,
    Quote,
    Tick,
    TradingResearchError,
    Venue,
)
from .dataset import (
    DataProviderPort,
    Dataset,
    DatasetVersion,
    InMemoryDataProvider,
    TemporalView,
    ValidationIssue,
    ValidationReport,
    event_sort_key,
)
from .identity import InstrumentIdentity, instrument_identity, instrument_identity_sha256
from .orders import (
    ExecutionPolicy,
    OrderAuthority,
    OrderIntent,
    OrderState,
    OrderType,
    RiskApprovedOrder,
    Side,
    SimulatedFill,
    apply_slippage,
    fee_for,
    order_authority_sha256,
)
from .paper_actions import (
    PAPER_ACCOUNT_INSPECT,
    PAPER_POSITIONS_INSPECT,
    paper_positions_definition,
    paper_positions_handler,
    paper_inspect_definition,
    paper_inspect_handler,
)
from .paper_core_permission import standing_paper_read_authorizer
from .persistence import TradingStateRepository
from .workspace_query import (
    PaperAccountView,
    PaperPositionView,
    PaperWorkspaceQuery,
    paper_state_provider,
)
from .replay import OrderUpdate, ReplayBook, ReplayPhase, SimulationExecutionEngine, TimeSlice
from .risk import PendingRiskOrder, RiskEngine, RiskLimits, RiskRejected, RiskState
from .strategy import DecisionContext, OrderStrategy, Strategy, StrategyDecision
from .time_waves import TimeWave, group_visible_time_waves

__all__ = [
    "AccountSnapshot",
    "AvailabilityCache",
    "Bar",
    "CausalityViolation",
    "DataProviderPort",
    "Dataset",
    "DatasetVersion",
    "DecisionContext",
    "EventTime",
    "ExecutionPolicy",
    "FeatureLineage",
    "FeaturePoint",
    "FutureAccessError",
    "InMemoryDataProvider",
    "Instrument",
    "InstrumentIdentity",
    "MarketEvent",
    "OddsSnapshot",
    "OrderAuthority",
    "OrderIntent",
    "OrderState",
    "OrderStrategy",
    "OrderType",
    "OrderUpdate",
    "OutcomeSettlement",
    "Partition",
    "PAPER_ACCOUNT_INSPECT",
    "PAPER_POSITIONS_INSPECT",
    "PaperAccountView",
    "PaperPositionView",
    "PaperWorkspaceQuery",
    "PendingRiskOrder",
    "PortfolioLedger",
    "Position",
    "Provenance",
    "Quote",
    "ReplayBook",
    "ReplayPhase",
    "RiskApprovedOrder",
    "RiskEngine",
    "RiskLimits",
    "RiskRejected",
    "RiskState",
    "Side",
    "SimulatedFill",
    "SimulationExecutionEngine",
    "Strategy",
    "StrategyDecision",
    "TemporalView",
    "Tick",
    "TimeSlice",
    "TimeWave",
    "TradingResearchError",
    "TradingStateRepository",
    "TrainOnlyStandardizer",
    "ValidationIssue",
    "ValidationReport",
    "Venue",
    "apply_slippage",
    "causal_shift",
    "event_sort_key",
    "fee_for",
    "fill_missing",
    "group_visible_time_waves",
    "instrument_identity",
    "instrument_identity_sha256",
    "order_authority_sha256",
    "paper_inspect_definition",
    "paper_inspect_handler",
    "paper_positions_definition",
    "paper_positions_handler",
    "standing_paper_read_authorizer",
    "paper_state_provider",
    "trailing_mean",
]
