"""Causality-first contracts for the paper-only AI Trader Research Lab."""

from .causality import (
    AvailabilityCache,
    FeatureLineage,
    FeaturePoint,
    TrainOnlyStandardizer,
    causal_shift,
    fill_missing,
    trailing_mean,
)
from .contracts import (
    Bar,
    CausalityViolation,
    EventTime,
    FutureAccessError,
    Instrument,
    MarketEvent,
    OddsSnapshot,
    OutcomeSettlement,
    Partition,
    Provenance,
    Quote,
    Tick,
    TradingResearchError,
    Venue,
)
from .dataset import (
    DataProviderPort,
    Dataset,
    DatasetVersion,
    InMemoryDataProvider,
    TemporalView,
    ValidationIssue,
    ValidationReport,
    event_sort_key,
)
from .strategy import DecisionContext, Strategy, StrategyDecision

__all__ = [
    "AvailabilityCache",
    "Bar",
    "CausalityViolation",
    "DataProviderPort",
    "Dataset",
    "DatasetVersion",
    "DecisionContext",
    "EventTime",
    "FeatureLineage",
    "FeaturePoint",
    "FutureAccessError",
    "InMemoryDataProvider",
    "Instrument",
    "MarketEvent",
    "OddsSnapshot",
    "OutcomeSettlement",
    "Partition",
    "Provenance",
    "Quote",
    "Strategy",
    "StrategyDecision",
    "TemporalView",
    "Tick",
    "TradingResearchError",
    "TrainOnlyStandardizer",
    "ValidationIssue",
    "ValidationReport",
    "Venue",
    "causal_shift",
    "event_sort_key",
    "fill_missing",
    "trailing_mean",
]
