"""Semantic-first computer interaction contracts."""

from .domain import (
    AmbiguousTargetError,
    ApplicationIdentity,
    BrowserContextIdentity,
    ControlLocator,
    ControlNode,
    FallbackReason,
    InteractionAction,
    InteractionEvidence,
    InteractionResult,
    InteractionTarget,
    PermissionBlockedError,
    SemanticSnapshot,
    StaleSnapshotError,
    TargetNotFoundError,
    UnsupportedInteractionError,
    WindowIdentity,
)
from .orchestration import (
    InteractionAdapter,
    InteractionReplayBlockedError,
    InteractionRequest,
    InteractionRisk,
    InteractionUncertainError,
    SemanticInteractionCoordinator,
)
from .playwright_adapter import (
    BrowserSession,
    DialogBroker,
    DialogRule,
    DownloadBroker,
    FrameScope,
    PageRegistry,
    PlaywrightInteractionAdapter,
)
from .resolver import resolve_strict, validate_snapshot
from .windows_uia_adapter import (
    PywinautoUIABackend,
    UIABackendMeasurement,
    UIAControlRecord,
    UIAWindowRecord,
    WindowsUIABackend,
    WindowsUIAInteractionAdapter,
    choose_measured_backend,
    measure_observation,
)

__all__ = [
    "AmbiguousTargetError",
    "ApplicationIdentity",
    "BrowserContextIdentity",
    "BrowserSession",
    "ControlLocator",
    "ControlNode",
    "DialogBroker",
    "DialogRule",
    "DownloadBroker",
    "FallbackReason",
    "FrameScope",
    "InteractionAction",
    "InteractionAdapter",
    "InteractionEvidence",
    "InteractionReplayBlockedError",
    "InteractionRequest",
    "InteractionResult",
    "InteractionRisk",
    "InteractionTarget",
    "InteractionUncertainError",
    "PageRegistry",
    "PermissionBlockedError",
    "PlaywrightInteractionAdapter",
    "PywinautoUIABackend",
    "SemanticInteractionCoordinator",
    "SemanticSnapshot",
    "StaleSnapshotError",
    "TargetNotFoundError",
    "UIABackendMeasurement",
    "UIAControlRecord",
    "UIAWindowRecord",
    "UnsupportedInteractionError",
    "WindowIdentity",
    "WindowsUIABackend",
    "WindowsUIAInteractionAdapter",
    "choose_measured_backend",
    "measure_observation",
    "resolve_strict",
    "validate_snapshot",
]
